// app/lang.ts
export const translations = {
  fr: {
    heroTitle: "Mathis Boche",
    heroDesc: "Communication & web chez ChessMates International. Joueur d’échecs.",
    contact: "Contact",
    parcours: "Parcours",
    aboutTitle: "À propos",
    aboutList: [
      "17 ans, lycéen à Montrouge",
      "Responsable communication, ChessMates International",
      "Animateur échecs (DAFFE 1)",
      "Joueur licencié à Bois-Colombes",
      "Intérêt pour l'entrepreneuriat et le web"
    ],
    expTitle: "Expériences",
    exp1Title: "ChessMates International",
    exp1Desc: "Gestion des réseaux sociaux et du site web depuis 2024",
    exp1Link: "chessmatesinternational.com",
    exp2Title: "DAFFE 1 — Animateur échecs",
    exp2Desc: "Diplômé en 2024, expérience à Bois-Colombes et à la Cité des sciences",
    exp2Link: "mtbh.fr/daffe",
    chessTitle: "Échecs",
    chessList: [
      "Classement FIDE : 1791 standard, 1743 rapide, 1694 blitz",
      "Club : Bois-Colombes",
      "Animateur à la Cité des sciences depuis 2025",
      "Deux participations aux Championnats de France Jeunes"
    ],
    contactTitle: "Contact",
    email: "mathis@boche.co",
    linkedIn: "LinkedIn",
    github: "GitHub",
    instagram: "Instagram",
    lastUpdate: "Dernière mise à jour : mai 2025 • Hébergé sur Vercel",
    back: "Retour",
    contactPageTitle: "Me contacter",
    emailLabel: "Email",
    callLabel: "Appeler",
    whatsappLabel: "WhatsApp",
    addContactLabel: "Ajouter à mes contacts",
    emailInfoLabel: "Email :",
    telInfoLabel: "Tel :",
    notFoundTitle: "Page introuvable.",
    notFoundDesc: "Ce lien semble brisé ou la page a été déplacée.",
    backHome: "Retour à l’accueil",
  },
  en: {
    heroTitle: "Mathis Boche",
    heroDesc: "Communications & web at ChessMates International. Chess player.",
    contact: "Contact",
    parcours: "Background",
    aboutTitle: "About",
    aboutList: [
      "17, student in Montrouge",
      "Communications, ChessMates International",
      "Certified chess instructor (DAFFE 1)",
      "Competitive player at Bois-Colombes",
      "Interested in entrepreneurship & web"
    ],
    expTitle: "Experience",
    exp1Title: "ChessMates International",
    exp1Desc: "Managing social media & website since 2024",
    exp1Link: "chessmatesinternational.com",
    exp2Title: "DAFFE 1 — Chess instructor",
    exp2Desc: "Certified in 2024, experience at Bois-Colombes & Cité des sciences",
    exp2Link: "mtbh.fr/daffe",
    chessTitle: "Chess",
    chessList: [
      "FIDE rating: 1791 standard, 1743 rapid, 1694 blitz",
      "Club: Bois-Colombes",
      "Instructor at Cité des sciences since 2025",
      "Two participations in French Youth Championships"
    ],
    contactTitle: "Contact",
    email: "mathis@boche.co",
    linkedIn: "LinkedIn",
    github: "GitHub",
    instagram: "Instagram",
    lastUpdate: "Last update: May 2025 • Hosted on Vercel",
    back: "Back",
    contactPageTitle: "Contact me",
    emailLabel: "Email",
    callLabel: "Call",
    whatsappLabel: "WhatsApp",
    addContactLabel: "Add to contacts",
    emailInfoLabel: "Email:",
    telInfoLabel: "Phone:",
    notFoundTitle: "Page not found.",
    notFoundDesc: "This link appears broken or the page has moved.",
    backHome: "Back home",
  }
};
