// app/lang.ts
export const translations = {
  fr: {
    heroTitle: "Mathis Boche",
    heroDesc: "Communication et web pour ChessMates International. Joueur d’échecs passionné.",
    contact: "Me contacter",
    parcours: "Voir mon parcours",
    aboutTitle: "À propos",
    aboutList: [
      "17 ans, lycéen à Montrouge",
      "Responsable communication ChessMates International",
      "DAFFE 1 — Animateur diplômé",
      "Joueur d’échecs de compétition, club de Bois-Colombes",
      "Entrepreneuriat & web, focus efficacité"
    ],
    expTitle: "Expériences",
    exp1Title: "ChessMates International",
    exp1Desc: "Responsable communication & site web (2024–…)",
    exp1Link: "chessmatesinternational.com",
    exp2Title: "DAFFE 1 — Animateur échecs",
    exp2Desc: "Diplômé en 2024, terrain à Bois-Colombes & Cité des sciences",
    exp2Link: "mtbh.fr/daffe",
    chessTitle: "Échecs",
    chessList: [
      "Classement FIDE : 1746 (standard), 1687 (rapide), 1694 (blitz)",
      "Club : Bois-Colombes",
      "Animateur à la Cité des sciences (depuis 2025)",
      "Deux championnats de France Jeunes"
    ],
    contactTitle: "Contact & réseaux",
    email: "mathis@boche.co",
    linkedIn: "LinkedIn",
    github: "GitHub",
    instagram: "Instagram",
    lastUpdate: "Dernière mise à jour : mai 2025 • Hébergé sur Vercel",  // ← Virgule ajoutée ici
    back: "Retour",
    contactPageTitle: "Me contacter",
    emailLabel: "Email",
    callLabel: "Appeler",
    whatsappLabel: "WhatsApp",
    addContactLabel: "Ajouter à mes contacts",
    emailInfoLabel: "Email :",
    telInfoLabel: "Tel :",
    notFoundTitle: "Oups ! Page introuvable.",
    notFoundDesc: "Le lien que vous avez suivi semble brisé ou la page a été déplacée.",
    backHome: "Retour à l’accueil",
  },
  en: {
    heroTitle: "Mathis Boche",
    heroDesc: "Communications & web for ChessMates International. Passionate chess player.",
    contact: "Contact me",
    parcours: "View my background",
    aboutTitle: "About",
    aboutList: [
      "17, high school student in Montrouge",
      "Communications lead, ChessMates International",
      "DAFFE 1 — Certified chess instructor",
      "Competitive chess player, Bois-Colombes club",
      "Entrepreneurship & web, efficiency focused"
    ],
    expTitle: "Experience",
    exp1Title: "ChessMates International",
    exp1Desc: "Communications & website manager (2024–…)",
    exp1Link: "chessmatesinternational.com",
    exp2Title: "DAFFE 1 — Chess Instructor",
    exp2Desc: "Certified in 2024, field at Bois-Colombes & Cité des sciences",
    exp2Link: "mtbh.fr/daffe",
    chessTitle: "Chess",
    chessList: [
      "FIDE rating: 1746 (standard), 1687 (rapid), 1694 (blitz)",
      "Club: Bois-Colombes",
      "Instructor at Cité des sciences (since 2025)",
      "Two French Youth Championships"
    ],
    contactTitle: "Contact & social",
    email: "mathis@boche.co",
    linkedIn: "LinkedIn",
    github: "GitHub",
    instagram: "Instagram",
    lastUpdate: "Last updated: May 2025 • Hosted on Vercel",  // ← Virgule ajoutée ici
    back: "Back",
    contactPageTitle: "Contact me",
    emailLabel: "Email",
    callLabel: "Call",
    whatsappLabel: "WhatsApp",
    addContactLabel: "Add to contacts",
    emailInfoLabel: "Email:",
    telInfoLabel: "Phone:",
    notFoundTitle: "Oops! Page not found.",
    notFoundDesc: "The link you followed seems broken or the page has been moved.",
    backHome: "Back to home",
  }
};
